Repository tigernetframework/Tigernet, pull requests merged in 2023-04, with the labels that each got.

#26 #7 Created initial data access layer
  .gitignore
  Tigernet.Samples.RestApi/Abstractions/IUserClever.cs
  Tigernet.Samples.RestApi/Clevers/Interfaces/IUserClever.cs
  Tigernet.Samples.RestApi/Clevers/UserClever.cs
  Tigernet.Samples.RestApi/Models/User.cs
  Tigernet.Samples.RestApi/Program.cs
  Tigernet.Samples.RestApi/Resters/UsersRester.cs
  src/Tigernet.Hosting/Actions/ResterBase.cs
  src/Tigernet.Hosting/Attributes/HttpMethods/Commons/HttpMethodAttribute.cs
  src/Tigernet.Hosting/Attributes/HttpMethods/GetterAttribute.cs
  src/Tigernet.Hosting/Attributes/HttpMethods/PosterAttribute.cs
  src/Tigernet.Hosting/Attributes/Query/SearchablePropertyAttribute.cs
  src/Tigernet.Hosting/DataAccess/Clevers/CleverBase.cs
  src/Tigernet.Hosting/DataAccess/Clevers/ICleverBase.cs
  src/Tigernet.Hosting/Extensions/EntityExtensions.cs
  src/Tigernet.Hosting/Extensions/ExpressionExtensions.cs
  src/Tigernet.Hosting/Extensions/QueryExtensions.cs
  src/Tigernet.Hosting/Extensions/QueryGeneratorExtensions.cs
  src/Tigernet.Hosting/Extensions/TypeExtensions.cs
  src/Tigernet.Hosting/Models/Common/IEntity.cs
  src/Tigernet.Hosting/Models/Common/IQueryableEntity.cs
  src/Tigernet.Hosting/Models/Query/EntityQueryOptions.cs
  src/Tigernet.Hosting/Models/Query/FilterOptions.cs
  src/Tigernet.Hosting/Models/Query/IEntityQueryOptions.cs
  src/Tigernet.Hosting/Models/Query/IQueryOptions.cs
  src/Tigernet.Hosting/Models/Query/IncludeOptions.cs
  src/Tigernet.Hosting/Models/Query/PaginationOptions.cs
  src/Tigernet.Hosting/Models/Query/PredicateBuilder.cs
  src/Tigernet.Hosting/Models/Query/QueryFilter.cs
  src/Tigernet.Hosting/Models/Query/QueryOptions.cs
  src/Tigernet.Hosting/Models/Query/SearchOptions.cs
  src/Tigernet.Hosting/Models/Query/SortOptions.cs
  src/Tigernet.Hosting/Tigernet.Hosting.csproj
  src/Tigernet.Hosting/TigernetHostBuilder.cs
Labels: enhancement, infrastructure

#50 Improve information about the framework missions
  README.md
Labels: documentation

#51 Create CONTRIBUTING.md
  CONTRIBUTING.md
Labels: documentation

#55 Changed default branch to main
  .github/workflows/ci.yml
Labels: good first issue

#61 #47 Implemented generic repository pattern and finished query extensions
  Tigernet.Samples.RestApi/Brokers/EfCoreDataStorageBroker.cs
  Tigernet.Samples.RestApi/Clevers/Interfaces/IUserClever.cs
  Tigernet.Samples.RestApi/Clevers/UserClever.cs
  Tigernet.Samples.RestApi/Models/User.cs
  Tigernet.Samples.RestApi/Program.cs
  Tigernet.Samples.RestApi/Resters/UsersRester.cs
  Tigernet.Samples.RestApi/Tigernet.Samples.RestApi.csproj
  docs/Architecture.drawio
  src/Tigernet.Hosting/Attributes/HttpMethods/Commons/HttpMethodAttribute.cs
  src/Tigernet.Hosting/Attributes/HttpMethods/DeleterAttribute.cs
  src/Tigernet.Hosting/Attributes/HttpMethods/GetterAttribute.cs
  src/Tigernet.Hosting/Attributes/HttpMethods/PatcherAttribute.cs
  src/Tigernet.Hosting/Attributes/HttpMethods/PosterAttribute.cs
  src/Tigernet.Hosting/Attributes/HttpMethods/PutterAttribute.cs
  src/Tigernet.Hosting/DataAccess/Brokers/IDataStorageBroker.cs
  src/Tigernet.Hosting/DataAccess/Clevers/CleverBase.cs
  src/Tigernet.Hosting/DataAccess/Clevers/ICleverBase.cs
  src/Tigernet.Hosting/DataAccess/Exceptions/EntityCreateException.cs
  src/Tigernet.Hosting/DataAccess/Exceptions/EntityDeleteException.cs
  src/Tigernet.Hosting/DataAccess/Exceptions/EntityNotFoundException.cs
  src/Tigernet.Hosting/DataAccess/Exceptions/EntityUpdateException.cs
  src/Tigernet.Hosting/DataAccess/Models/Entity/IEntity.cs
  src/Tigernet.Hosting/DataAccess/Models/Entity/IQueryableEntity.cs
  src/Tigernet.Hosting/DataAccess/Models/Query/EntityExtensions.cs
  src/Tigernet.Hosting/DataAccess/Models/Query/EntityQueryOptions.cs
  src/Tigernet.Hosting/DataAccess/Models/Query/ExpressionExtensions.cs
  src/Tigernet.Hosting/DataAccess/Models/Query/PredicateBuilder.cs
  src/Tigernet.Hosting/DataAccess/Models/Query/QueryExtensions.cs
  src/Tigernet.Hosting/DataAccess/Models/Query/QueryGeneratorExtensions.cs
  src/Tigernet.Hosting/DataAccess/Models/Query/TypeExtensions.cs
  src/Tigernet.Hosting/DataAccess/Models/QueryOptions/FilterOptions.cs
  src/Tigernet.Hosting/DataAccess/Models/QueryOptions/IEntityQueryOptions.cs
  src/Tigernet.Hosting/DataAccess/Models/QueryOptions/IQueryOptions.cs
  src/Tigernet.Hosting/DataAccess/Models/QueryOptions/IncludeOptions.cs
  src/Tigernet.Hosting/DataAccess/Models/QueryOptions/PaginationOptions.cs
  src/Tigernet.Hosting/DataAccess/Models/QueryOptions/QueryFilter.cs
  src/Tigernet.Hosting/DataAccess/Models/QueryOptions/QueryOptions.cs
  src/Tigernet.Hosting/DataAccess/Models/QueryOptions/SearchOptions.cs
  src/Tigernet.Hosting/DataAccess/Models/QueryOptions/SortOptions.cs
  src/Tigernet.Hosting/DataAccess/Services/EntityManagerBaseService.cs
  src/Tigernet.Hosting/DataAccess/Services/IEntityManagerBaseService.cs
  src/Tigernet.Hosting/Models/Common/IEntity.cs
  src/Tigernet.Hosting/Models/Query/FilterOptions.cs
  src/Tigernet.Hosting/Models/Query/IncludeOptions.cs
  src/Tigernet.Hosting/Tigernet.Hosting.csproj
  src/Tigernet.Hosting/TigernetHostBuilder.DI.cs
  src/Tigernet.Hosting/TigernetHostBuilder.cs
Labels: infrastructure
